### ISSUE TITLE
Maven dependency isn't working

### ISSUE THREAD

**Issue by ghost** [aesy/musicbrainz-api-client#1]
The maeven link to the repository dependency isn't working. Amazing library!

**Comment by aesy** [comment]
Hey, thanks for checking out the repo. The library isn't finished yet so it isn't actually published, although the readme makes it seem otherwise. I haven't touched it in a few months now, but I do intend to get back to it soon.

**Comment by ghost** [comment]
Thanks. Nice to know. As soon as it get finished i will use it. Regards

**Comment by Matrix89** [comment]
Any update?

**Comment by CatPlanet** [comment]
Hi. It seems it's pretty complete to me.
Would be really cool and convenient if you could publish your library.

We can always pull request patches if something changes 👍

**Comment by aesy** [comment]
@CatPlanet Yeah, you're right. Sometime soon I'll have a look through the project to see if there's anything that's blocking me from publishing it, otherwise I'll publish it.

**Comment by aesy** [comment]
Sorry for the delay, I had some trouble with the deployment. It's done now though and should be accessible via maven central. I've updated the readme with installation instructions. Let me know if you run into any problems! :tada:

**Comment by janisfolkbergs** [comment]
The maven link to the repository dependency still isn't working.

**Comment by aesy** [comment]
@Egame89 Thanks for mentioning that, I just checked and apparently I only pushed it as a snapshot and staged a release. Not sure what happened there, but it's now available as a [proper release](https://central.sonatype.com/artifact/io.aesy.musicbrainz/musicbrainz-api-jersey-client/1.0.0/overview).
